// Original noun list for this app. Not the published Codenames deck.
export const WORDS = Object.freeze([
  'anchor', 'apple', 'arrow', 'atlas', 'badge', 'balloon', 'barn', 'barrel',
  'beach', 'beacon', 'bear', 'bell', 'berry', 'bicycle', 'blade', 'blanket',
  'blizzard', 'board', 'boat', 'bolt', 'book', 'boot', 'bottle', 'boulder',
  'bow', 'box', 'branch', 'brass', 'bread', 'bridge', 'brook', 'broom',
  'brush', 'bucket', 'buffalo', 'bugle', 'bulb', 'bunk', 'butter', 'button',
  'cabin', 'cable', 'cactus', 'cake', 'camel', 'camp', 'candle', 'cannon',
  'canoe', 'canvas', 'cape', 'captain', 'card', 'carpet', 'carrot', 'castle',
  'cave', 'chain', 'chair', 'chalk', 'chart', 'cheese', 'cherry', 'chess',
  'chest', 'chimney', 'circle', 'cliff', 'cloak', 'clock', 'cloud', 'club',
  'coal', 'coast', 'coin', 'comet', 'compass', 'copper', 'cord', 'cork',
  'corn', 'cottage', 'couch', 'cougar', 'court', 'crane', 'creek', 'crew',
  'crown', 'crystal', 'cup', 'curtain', 'daisy', 'dance', 'dart', 'dawn',
  'deck', 'deer', 'desert', 'desk', 'diamond', 'dice', 'ditch', 'dock',
  'doll', 'donkey', 'door', 'dragon', 'drum', 'duck', 'dune', 'dust',
  'eagle', 'earth', 'eclipse', 'engine', 'falcon', 'fence', 'field', 'fire',
  'fish', 'flag', 'flame', 'flask', 'flood', 'floor', 'flute', 'fog',
  'forest', 'fork', 'fort', 'fountain', 'fox', 'frame', 'frost', 'garden',
  'gate', 'gear', 'ghost', 'giant', 'glacier', 'glass', 'glove', 'goat',
  'gold', 'goose', 'grain', 'grass', 'grave', 'guitar', 'gulf', 'hammer',
  'harbor', 'harp', 'hat', 'hawk', 'hazel', 'heart', 'hedge', 'helmet',
  'hill', 'hive', 'honey', 'hood', 'hook', 'horn', 'horse', 'hotel',
  'hound', 'house', 'iceberg', 'ink', 'iron', 'island', 'ivory', 'jacket',
  'jaguar', 'jam', 'jet', 'jewel', 'judge', 'jungle', 'kettle', 'key',
  'king', 'kite', 'knife', 'knight', 'knot', 'ladder', 'lake', 'lamp',
  'lark', 'laser', 'leaf', 'lemon', 'letter', 'lighthouse', 'lily', 'lime',
  'line', 'lion', 'lock', 'log', 'loom', 'magnet', 'maple', 'marble',
  'march', 'mark', 'mask', 'match', 'meadow', 'mercury', 'mine', 'mint',
  'mirror', 'mole', 'moon', 'moose', 'moth', 'motor', 'mountain', 'mouse',
  'mug', 'nail', 'needle', 'nest', 'net', 'night', 'novel', 'nurse',
  'nut', 'oak', 'oar', 'ocean', 'oil', 'olive', 'opera', 'orange',
  'orbit', 'orchard', 'organ', 'ostrich', 'otter', 'owl', 'paddle', 'palace',
  'palm', 'pan', 'paper', 'parade', 'park', 'parrot', 'patch', 'pearl',
  'pen', 'pencil', 'penguin', 'pepper', 'piano', 'pilot', 'pin', 'pine',
  'pipe', 'pirate', 'pitch', 'plane', 'planet', 'plank', 'plate', 'plaza',
  'plot', 'pocket', 'poem', 'point', 'pole', 'pond', 'pony', 'port',
  'post', 'powder', 'prince', 'prism', 'pump', 'pyramid', 'queen', 'rabbit',
  'racket', 'radio', 'raft', 'rail', 'rain', 'rake', 'ram', 'ramp',
  'raven', 'ray', 'record', 'reef', 'ring', 'river', 'road', 'robe',
  'rock', 'rocket', 'rod', 'roof', 'root', 'rope', 'rose', 'ruby',
  'rug', 'ruler', 'saddle', 'sail', 'salt', 'sand', 'scale', 'school',
  'scorpion', 'screen', 'screw', 'scroll', 'seal', 'seed', 'shark', 'shed',
  'sheep', 'shell', 'ship', 'shoe', 'shop', 'shovel', 'silk', 'silver',
  'sink', 'sketch', 'ski', 'skull', 'sled', 'slope', 'smoke', 'snake',
  'snow', 'soap', 'sock', 'soldier', 'sound', 'soup', 'spark', 'spell',
  'spider', 'spike', 'spoon', 'spot', 'spring', 'spy', 'square', 'stable',
  'staff', 'stage', 'stamp', 'star', 'steam', 'steel', 'stick', 'stock',
  'storm', 'straw', 'stream', 'street', 'string', 'suit', 'summer', 'sun',
  'swamp', 'swan', 'swing', 'switch', 'sword', 'table', 'tag', 'tail',
  'tank', 'teacher', 'telescope', 'temple', 'tent', 'theater', 'thief', 'thumb',
  'thunder', 'ticket', 'tide', 'tiger', 'tile', 'toast', 'tooth', 'torch',
  'tower', 'track', 'trail', 'train', 'trap', 'tree', 'triangle', 'trip',
  'trumpet', 'trunk', 'tube', 'tunnel', 'turkey', 'turtle', 'umbrella', 'unicorn',
  'uniform', 'valley', 'vampire', 'van', 'vase', 'vault', 'veil', 'velvet',
  'violin', 'volcano', 'wagon', 'wall', 'walnut', 'wand', 'warehouse', 'watch',
  'water', 'wave', 'web', 'whale', 'wheat', 'wheel', 'whip', 'whistle',
  'wind', 'window', 'wing', 'winter', 'wire', 'witch', 'wolf', 'wood',
  'wool', 'worm', 'yard', 'yarn', 'zebra', 'zipper',
]);

const seen = new Set();
for (const word of WORDS) {
  if (seen.has(word)) {
    throw new Error(`Duplicate word: ${word}`);
  }
  seen.add(word);
}
